name: fintech_app
description: Mobile Banking App.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_storage: ^2.0.2
  line_icons: ^2.0.1
  lint: ^1.5.3
  provider: ^5.0.0
  data_table_2: ^2.1.0
  google_fonts: ^2.1.0
  dio: ^4.0.0
  intl: ^0.17.0
  boxicons: ^2.1.3
  material_design_icons_flutter: ^4.0.5955
  simple_tooltip: ^0.1.16
  flutter_screenutil: ^5.0.0+2
  device_preview: ^0.7.4
  styled_widget: ^0.4.0+3
  flutter_svg: ^0.22.0
  grouped_list: ^4.1.0
  substring_highlight: ^1.0.33
  equatable: ^2.0.3
  modal_bottom_sheet: ^2.0.0
  date_ranger: ^0.0.1
  charts_flutter:
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter

dev_dependencies:
  flutter_native_splash: ^1.2.4
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/images/logo.png
  color: "#FFFFFF"
  android: true
  ios: true

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
  uses-material-design: true
